#pragma once

// Generated canonical contract include for the rocm backend.
// Native optimized APIs remain backend-owned behind this adapter surface.

#include "quixicore/contract/kernel_abi.hpp"
#include "quixicore/contract/operations.hpp"
#include "quixicore/rocm/contract_stubs.hpp"

namespace quixicore::rocm::contract_api {

[[nodiscard]] inline quixicore::contract::Status dispatch(
    quixicore::contract::OperationId operation,
    const quixicore::contract::KernelCall& call) noexcept {
  switch (operation) {
    case quixicore::contract::OperationId::act_quant_int8:
      return quixicore::rocm::contract_stubs::act_quant_int8(call);
    case quixicore::contract::OperationId::adamw:
      return quixicore::rocm::contract_stubs::adamw(call);
    case quixicore::contract::OperationId::adaptive_norm_modulation:
      return quixicore::rocm::contract_stubs::adaptive_norm_modulation(call);
    case quixicore::contract::OperationId::adaptive_norm_modulation_qkv:
      return quixicore::rocm::contract_stubs::adaptive_norm_modulation_qkv(call);
    case quixicore::contract::OperationId::adaptive_rms_norm_modulation:
      return quixicore::rocm::contract_stubs::adaptive_rms_norm_modulation(call);
    case quixicore::contract::OperationId::adaptive_rms_norm_modulation_qkv:
      return quixicore::rocm::contract_stubs::adaptive_rms_norm_modulation_qkv(call);
    case quixicore::contract::OperationId::all_gather_gemm:
      return quixicore::rocm::contract_stubs::all_gather_gemm(call);
    case quixicore::contract::OperationId::all_reduce_rms_norm:
      return quixicore::rocm::contract_stubs::all_reduce_rms_norm(call);
    case quixicore::contract::OperationId::argmax:
      return quixicore::rocm::contract_stubs::argmax(call);
    case quixicore::contract::OperationId::attention_gate_residual:
      return quixicore::rocm::contract_stubs::attention_gate_residual(call);
    case quixicore::contract::OperationId::attention_with_lse:
      return quixicore::rocm::contract_stubs::attention_with_lse(call);
    case quixicore::contract::OperationId::audio_conv1d:
      return quixicore::rocm::contract_stubs::audio_conv1d(call);
    case quixicore::contract::OperationId::audio_resample:
      return quixicore::rocm::contract_stubs::audio_resample(call);
    case quixicore::contract::OperationId::causal_conv3d_cache_update:
      return quixicore::rocm::contract_stubs::causal_conv3d_cache_update(call);
    case quixicore::contract::OperationId::causal_conv_gate_residual:
      return quixicore::rocm::contract_stubs::causal_conv_gate_residual(call);
    case quixicore::contract::OperationId::classifier_free_guidance_combine:
      return quixicore::rocm::contract_stubs::classifier_free_guidance_combine(call);
    case quixicore::contract::OperationId::classifier_free_guidance_scheduler_step:
      return quixicore::rocm::contract_stubs::classifier_free_guidance_scheduler_step(call);
    case quixicore::contract::OperationId::conv_transpose_overlap_add:
      return quixicore::rocm::contract_stubs::conv_transpose_overlap_add(call);
    case quixicore::contract::OperationId::cross_entropy:
      return quixicore::rocm::contract_stubs::cross_entropy(call);
    case quixicore::contract::OperationId::cross_entropy_backward:
      return quixicore::rocm::contract_stubs::cross_entropy_backward(call);
    case quixicore::contract::OperationId::ctc_decode:
      return quixicore::rocm::contract_stubs::ctc_decode(call);
    case quixicore::contract::OperationId::deformable_attention:
      return quixicore::rocm::contract_stubs::deformable_attention(call);
    case quixicore::contract::OperationId::deterministic_noise:
      return quixicore::rocm::contract_stubs::deterministic_noise(call);
    case quixicore::contract::OperationId::diffusion_scheduler_step:
      return quixicore::rocm::contract_stubs::diffusion_scheduler_step(call);
    case quixicore::contract::OperationId::down_projection_residual:
      return quixicore::rocm::contract_stubs::down_projection_residual(call);
    case quixicore::contract::OperationId::downsample_3d:
      return quixicore::rocm::contract_stubs::downsample_3d(call);
    case quixicore::contract::OperationId::downsample_conv2d:
      return quixicore::rocm::contract_stubs::downsample_conv2d(call);
    case quixicore::contract::OperationId::dropout:
      return quixicore::rocm::contract_stubs::dropout(call);
    case quixicore::contract::OperationId::embedding_backward:
      return quixicore::rocm::contract_stubs::embedding_backward(call);
    case quixicore::contract::OperationId::embedding_lookup:
      return quixicore::rocm::contract_stubs::embedding_lookup(call);
    case quixicore::contract::OperationId::flow_euler_step:
      return quixicore::rocm::contract_stubs::flow_euler_step(call);
    case quixicore::contract::OperationId::flow_step_action_clamp_denormalize:
      return quixicore::rocm::contract_stubs::flow_step_action_clamp_denormalize(call);
    case quixicore::contract::OperationId::fp8_gemm:
      return quixicore::rocm::contract_stubs::fp8_gemm(call);
    case quixicore::contract::OperationId::gate_up_projection_swiglu:
      return quixicore::rocm::contract_stubs::gate_up_projection_swiglu(call);
    case quixicore::contract::OperationId::geglu_projection:
      return quixicore::rocm::contract_stubs::geglu_projection(call);
    case quixicore::contract::OperationId::gelu:
      return quixicore::rocm::contract_stubs::gelu(call);
    case quixicore::contract::OperationId::gelu_backward:
      return quixicore::rocm::contract_stubs::gelu_backward(call);
    case quixicore::contract::OperationId::gguf_gemv:
      return quixicore::rocm::contract_stubs::gguf_gemv(call);
    case quixicore::contract::OperationId::glu:
      return quixicore::rocm::contract_stubs::glu(call);
    case quixicore::contract::OperationId::grammar_mask:
      return quixicore::rocm::contract_stubs::grammar_mask(call);
    case quixicore::contract::OperationId::grid_sample:
      return quixicore::rocm::contract_stubs::grid_sample(call);
    case quixicore::contract::OperationId::group_norm_silu:
      return quixicore::rocm::contract_stubs::group_norm_silu(call);
    case quixicore::contract::OperationId::hadamard:
      return quixicore::rocm::contract_stubs::hadamard(call);
    case quixicore::contract::OperationId::indexer_k_gather:
      return quixicore::rocm::contract_stubs::indexer_k_gather(call);
    case quixicore::contract::OperationId::istft:
      return quixicore::rocm::contract_stubs::istft(call);
    case quixicore::contract::OperationId::joint_multimodal_attention:
      return quixicore::rocm::contract_stubs::joint_multimodal_attention(call);
    case quixicore::contract::OperationId::kv_cache_compact:
      return quixicore::rocm::contract_stubs::kv_cache_compact(call);
    case quixicore::contract::OperationId::kv_cache_copy_blocks_q8_0:
      return quixicore::rocm::contract_stubs::kv_cache_copy_blocks_q8_0(call);
    case quixicore::contract::OperationId::kv_cache_gather:
      return quixicore::rocm::contract_stubs::kv_cache_gather(call);
    case quixicore::contract::OperationId::kv_cache_gather_q8_0:
      return quixicore::rocm::contract_stubs::kv_cache_gather_q8_0(call);
    case quixicore::contract::OperationId::kv_cache_offload:
      return quixicore::rocm::contract_stubs::kv_cache_offload(call);
    case quixicore::contract::OperationId::kv_cache_scatter:
      return quixicore::rocm::contract_stubs::kv_cache_scatter(call);
    case quixicore::contract::OperationId::kv_cache_scatter_q8_0:
      return quixicore::rocm::contract_stubs::kv_cache_scatter_q8_0(call);
    case quixicore::contract::OperationId::linear_attention:
      return quixicore::rocm::contract_stubs::linear_attention(call);
    case quixicore::contract::OperationId::log_mel_spectrogram:
      return quixicore::rocm::contract_stubs::log_mel_spectrogram(call);
    case quixicore::contract::OperationId::logits_bias_penalties_top_k_top_p_sample:
      return quixicore::rocm::contract_stubs::logits_bias_penalties_top_k_top_p_sample(call);
    case quixicore::contract::OperationId::lora_apply:
      return quixicore::rocm::contract_stubs::lora_apply(call);
    case quixicore::contract::OperationId::lowbit_gemv:
      return quixicore::rocm::contract_stubs::lowbit_gemv(call);
    case quixicore::contract::OperationId::masked_mean_pool_rms_l2:
      return quixicore::rocm::contract_stubs::masked_mean_pool_rms_l2(call);
    case quixicore::contract::OperationId::mixed_prefill_decode_attention:
      return quixicore::rocm::contract_stubs::mixed_prefill_decode_attention(call);
    case quixicore::contract::OperationId::moe_all_to_all_dispatch:
      return quixicore::rocm::contract_stubs::moe_all_to_all_dispatch(call);
    case quixicore::contract::OperationId::moe_grouped_gemm_swiglu:
      return quixicore::rocm::contract_stubs::moe_grouped_gemm_swiglu(call);
    case quixicore::contract::OperationId::moe_route_top_k_prefix_sum_permute:
      return quixicore::rocm::contract_stubs::moe_route_top_k_prefix_sum_permute(call);
    case quixicore::contract::OperationId::moe_route_topk:
      return quixicore::rocm::contract_stubs::moe_route_topk(call);
    case quixicore::contract::OperationId::moe_unpermute_weighted_reduce:
      return quixicore::rocm::contract_stubs::moe_unpermute_weighted_reduce(call);
    case quixicore::contract::OperationId::mrope:
      return quixicore::rocm::contract_stubs::mrope(call);
    case quixicore::contract::OperationId::multi_codebook_sample:
      return quixicore::rocm::contract_stubs::multi_codebook_sample(call);
    case quixicore::contract::OperationId::multimodal_rope_nd:
      return quixicore::rocm::contract_stubs::multimodal_rope_nd(call);
    case quixicore::contract::OperationId::multimodal_stream_deinterleave:
      return quixicore::rocm::contract_stubs::multimodal_stream_deinterleave(call);
    case quixicore::contract::OperationId::multimodal_stream_interleave:
      return quixicore::rocm::contract_stubs::multimodal_stream_interleave(call);
    case quixicore::contract::OperationId::multistream_logits_codebook_sample:
      return quixicore::rocm::contract_stubs::multistream_logits_codebook_sample(call);
    case quixicore::contract::OperationId::non_max_suppression:
      return quixicore::rocm::contract_stubs::non_max_suppression(call);
    case quixicore::contract::OperationId::nvfp4_gemv:
      return quixicore::rocm::contract_stubs::nvfp4_gemv(call);
    case quixicore::contract::OperationId::overlap_add:
      return quixicore::rocm::contract_stubs::overlap_add(call);
    case quixicore::contract::OperationId::paged_attention_output_projection_residual:
      return quixicore::rocm::contract_stubs::paged_attention_output_projection_residual(call);
    case quixicore::contract::OperationId::paged_attention_q8_0:
      return quixicore::rocm::contract_stubs::paged_attention_q8_0(call);
    case quixicore::contract::OperationId::patchify_nd:
      return quixicore::rocm::contract_stubs::patchify_nd(call);
    case quixicore::contract::OperationId::patchify_projection_position:
      return quixicore::rocm::contract_stubs::patchify_projection_position(call);
    case quixicore::contract::OperationId::pixel_shuffle:
      return quixicore::rocm::contract_stubs::pixel_shuffle(call);
    case quixicore::contract::OperationId::prefix_append_attention:
      return quixicore::rocm::contract_stubs::prefix_append_attention(call);
    case quixicore::contract::OperationId::qk_norm_rope_attention:
      return quixicore::rocm::contract_stubs::qk_norm_rope_attention(call);
    case quixicore::contract::OperationId::qk_norm_rope_positioned:
      return quixicore::rocm::contract_stubs::qk_norm_rope_positioned(call);
    case quixicore::contract::OperationId::qkv_projection_qk_norm_rope_kv_append:
      return quixicore::rocm::contract_stubs::qkv_projection_qk_norm_rope_kv_append(call);
    case quixicore::contract::OperationId::quantize_int4_group:
      return quixicore::rocm::contract_stubs::quantize_int4_group(call);
    case quixicore::contract::OperationId::ragged_pack:
      return quixicore::rocm::contract_stubs::ragged_pack(call);
    case quixicore::contract::OperationId::ragged_unpack:
      return quixicore::rocm::contract_stubs::ragged_unpack(call);
    case quixicore::contract::OperationId::reduce_scatter_gemm:
      return quixicore::rocm::contract_stubs::reduce_scatter_gemm(call);
    case quixicore::contract::OperationId::residual_rms_norm_quant:
      return quixicore::rocm::contract_stubs::residual_rms_norm_quant(call);
    case quixicore::contract::OperationId::residual_vector_quantize_decode:
      return quixicore::rocm::contract_stubs::residual_vector_quantize_decode(call);
    case quixicore::contract::OperationId::residual_vector_quantize_encode:
      return quixicore::rocm::contract_stubs::residual_vector_quantize_encode(call);
    case quixicore::contract::OperationId::resize_bicubic:
      return quixicore::rocm::contract_stubs::resize_bicubic(call);
    case quixicore::contract::OperationId::resize_bilinear:
      return quixicore::rocm::contract_stubs::resize_bilinear(call);
    case quixicore::contract::OperationId::resize_normalize_layout_quant:
      return quixicore::rocm::contract_stubs::resize_normalize_layout_quant(call);
    case quixicore::contract::OperationId::rms_norm_backward:
      return quixicore::rocm::contract_stubs::rms_norm_backward(call);
    case quixicore::contract::OperationId::rnnt_beam_step:
      return quixicore::rocm::contract_stubs::rnnt_beam_step(call);
    case quixicore::contract::OperationId::rnnt_joiner:
      return quixicore::rocm::contract_stubs::rnnt_joiner(call);
    case quixicore::contract::OperationId::roi_align:
      return quixicore::rocm::contract_stubs::roi_align(call);
    case quixicore::contract::OperationId::rope_3d:
      return quixicore::rocm::contract_stubs::rope_3d(call);
    case quixicore::contract::OperationId::rotary_positioned:
      return quixicore::rocm::contract_stubs::rotary_positioned(call);
    case quixicore::contract::OperationId::rvq_distance_argmin_residual_update:
      return quixicore::rocm::contract_stubs::rvq_distance_argmin_residual_update(call);
    case quixicore::contract::OperationId::sample_categorical:
      return quixicore::rocm::contract_stubs::sample_categorical(call);
    case quixicore::contract::OperationId::selective_scan:
      return quixicore::rocm::contract_stubs::selective_scan(call);
    case quixicore::contract::OperationId::silu:
      return quixicore::rocm::contract_stubs::silu(call);
    case quixicore::contract::OperationId::speculative_verify_accept_compact_kv:
      return quixicore::rocm::contract_stubs::speculative_verify_accept_compact_kv(call);
    case quixicore::contract::OperationId::stft:
      return quixicore::rocm::contract_stubs::stft(call);
    case quixicore::contract::OperationId::streaming_conv1d_state:
      return quixicore::rocm::contract_stubs::streaming_conv1d_state(call);
    case quixicore::contract::OperationId::swiglu_oai:
      return quixicore::rocm::contract_stubs::swiglu_oai(call);
    case quixicore::contract::OperationId::temporal_upsample_conv3d:
      return quixicore::rocm::contract_stubs::temporal_upsample_conv3d(call);
    case quixicore::contract::OperationId::top_k_sample:
      return quixicore::rocm::contract_stubs::top_k_sample(call);
    case quixicore::contract::OperationId::unpatchify_nd:
      return quixicore::rocm::contract_stubs::unpatchify_nd(call);
    case quixicore::contract::OperationId::upsample_3d:
      return quixicore::rocm::contract_stubs::upsample_3d(call);
    case quixicore::contract::OperationId::upsample_conv2d:
      return quixicore::rocm::contract_stubs::upsample_conv2d(call);
    case quixicore::contract::OperationId::window_rfft_power_mel_log:
      return quixicore::rocm::contract_stubs::window_rfft_power_mel_log(call);
    default:
      break;
  }
  const auto name = quixicore::contract::operation_name(operation);
  return quixicore::contract::adapter_not_wired(
      name.empty() ? "unknown_operation" : name.data());
}

}  // namespace quixicore::rocm::contract_api
