#pragma once

// Generated by QuixiCore/tools/sync_kernel_contract.rb. Do not edit.
// These adapters are scaffolding only and make no implementation claim.

#include <array>

#include "quixicore/contract/kernel_abi.hpp"

namespace quixicore::rocm::contract_stubs {

using quixicore::contract::KernelCall;
using quixicore::contract::Status;
using quixicore::contract::StubDescriptor;

[[nodiscard]] inline Status act_quant_int8(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("act_quant_int8", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status adamw(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adamw", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status adaptive_norm_modulation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_norm_modulation", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_norm_modulation_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_norm_modulation_qkv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_rms_norm_modulation(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_rms_norm_modulation", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status adaptive_rms_norm_modulation_qkv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("adaptive_rms_norm_modulation_qkv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status all_gather_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("all_gather_gemm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status all_reduce_rms_norm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("all_reduce_rms_norm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status argmax(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("argmax", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status attention_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_gate_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status attention_with_lse(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("attention_with_lse", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status audio_conv1d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_conv1d", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status audio_resample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("audio_resample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status causal_conv3d_cache_update(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("causal_conv3d_cache_update", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status causal_conv_gate_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("causal_conv_gate_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status classifier_free_guidance_combine(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("classifier_free_guidance_combine", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status classifier_free_guidance_scheduler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("classifier_free_guidance_scheduler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status conv_transpose_overlap_add(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("conv_transpose_overlap_add", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status cross_entropy(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cross_entropy", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status cross_entropy_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("cross_entropy_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ctc_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ctc_decode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status deformable_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("deformable_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status deterministic_noise(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("deterministic_noise", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status diffusion_scheduler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("diffusion_scheduler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status down_projection_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("down_projection_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status downsample_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("downsample_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status downsample_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("downsample_conv2d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status dropout(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("dropout", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status embedding_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("embedding_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status embedding_lookup(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("embedding_lookup", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status flow_euler_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("flow_euler_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status flow_step_action_clamp_denormalize(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("flow_step_action_clamp_denormalize", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status fp8_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("fp8_gemm", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gate_up_projection_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gate_up_projection_swiglu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status geglu_projection(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("geglu_projection", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status gelu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gelu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gelu_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gelu_backward", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status gguf_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("gguf_gemv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status glu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("glu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status grammar_mask(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grammar_mask", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status grid_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("grid_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status group_norm_silu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("group_norm_silu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status hadamard(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("hadamard", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status indexer_k_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("indexer_k_gather", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status istft(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("istft", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status joint_multimodal_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("joint_multimodal_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_compact(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_compact", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_copy_blocks_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_copy_blocks_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_gather(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_gather", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_gather_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_gather_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_offload(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_offload", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status kv_cache_scatter(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_scatter", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status kv_cache_scatter_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("kv_cache_scatter_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status linear_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("linear_attention", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status log_mel_spectrogram(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("log_mel_spectrogram", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status logits_bias_penalties_top_k_top_p_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("logits_bias_penalties_top_k_top_p_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status lora_apply(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lora_apply", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status lowbit_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("lowbit_gemv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status masked_mean_pool_rms_l2(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("masked_mean_pool_rms_l2", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status mixed_prefill_decode_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mixed_prefill_decode_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_all_to_all_dispatch(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_all_to_all_dispatch", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_grouped_gemm_swiglu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_grouped_gemm_swiglu", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_route_top_k_prefix_sum_permute(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_top_k_prefix_sum_permute", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status moe_route_topk(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_route_topk", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status moe_unpermute_weighted_reduce(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("moe_unpermute_weighted_reduce", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status mrope(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("mrope", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status multi_codebook_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multi_codebook_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_rope_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_rope_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_stream_deinterleave(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_stream_deinterleave", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multimodal_stream_interleave(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multimodal_stream_interleave", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status multistream_logits_codebook_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("multistream_logits_codebook_sample", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status non_max_suppression(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("non_max_suppression", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status nvfp4_gemv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("nvfp4_gemv", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status overlap_add(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("overlap_add", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status paged_attention_output_projection_residual(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_output_projection_residual", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status paged_attention_q8_0(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("paged_attention_q8_0", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status patchify_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patchify_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status patchify_projection_position(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("patchify_projection_position", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status pixel_shuffle(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("pixel_shuffle", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status prefix_append_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("prefix_append_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status qk_norm_rope_attention(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope_attention", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status qk_norm_rope_positioned(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qk_norm_rope_positioned", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status qkv_projection_qk_norm_rope_kv_append(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("qkv_projection_qk_norm_rope_kv_append", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status quantize_int4_group(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("quantize_int4_group", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status ragged_pack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ragged_pack", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status ragged_unpack(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("ragged_unpack", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status reduce_scatter_gemm(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("reduce_scatter_gemm", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_rms_norm_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_rms_norm_quant", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_vector_quantize_decode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_vector_quantize_decode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status residual_vector_quantize_encode(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("residual_vector_quantize_encode", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_bicubic(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_bicubic", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_bilinear(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_bilinear", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status resize_normalize_layout_quant(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("resize_normalize_layout_quant", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rms_norm_backward(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rms_norm_backward", "family-only metadata; canonical adapter not wired");
}

[[nodiscard]] inline Status rnnt_beam_step(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rnnt_beam_step", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rnnt_joiner(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rnnt_joiner", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status roi_align(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("roi_align", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rope_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rope_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status rotary_positioned(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rotary_positioned", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status rvq_distance_argmin_residual_update(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("rvq_distance_argmin_residual_update", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status sample_categorical(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("sample_categorical", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status selective_scan(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("selective_scan", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status silu(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("silu", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status speculative_verify_accept_compact_kv(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("speculative_verify_accept_compact_kv", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status stft(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("stft", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status streaming_conv1d_state(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("streaming_conv1d_state", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status swiglu_oai(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("swiglu_oai", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status temporal_upsample_conv3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("temporal_upsample_conv3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status top_k_sample(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("top_k_sample", "partial family; canonical operation not implemented");
}

[[nodiscard]] inline Status unpatchify_nd(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("unpatchify_nd", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upsample_3d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upsample_3d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status upsample_conv2d(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("upsample_conv2d", "planned contract; no backend implementation evidence");
}

[[nodiscard]] inline Status window_rfft_power_mel_log(const KernelCall&) noexcept {
  return quixicore::contract::not_implemented("window_rfft_power_mel_log", "planned contract; no backend implementation evidence");
}

inline constexpr std::array<StubDescriptor, 113> kStubs{{
    {"act_quant_int8", "quantization", "partial family; canonical operation not implemented", &act_quant_int8},
    {"adamw", "optimizers", "partial family; canonical operation not implemented", &adamw},
    {"adaptive_norm_modulation", "diffusion", "planned contract; no backend implementation evidence", &adaptive_norm_modulation},
    {"adaptive_norm_modulation_qkv", "diffusion", "planned contract; no backend implementation evidence", &adaptive_norm_modulation_qkv},
    {"adaptive_rms_norm_modulation", "diffusion", "planned contract; no backend implementation evidence", &adaptive_rms_norm_modulation},
    {"adaptive_rms_norm_modulation_qkv", "diffusion", "planned contract; no backend implementation evidence", &adaptive_rms_norm_modulation_qkv},
    {"all_gather_gemm", "collectives", "planned contract; no backend implementation evidence", &all_gather_gemm},
    {"all_reduce_rms_norm", "collectives", "planned contract; no backend implementation evidence", &all_reduce_rms_norm},
    {"argmax", "sampling", "partial family; canonical operation not implemented", &argmax},
    {"attention_gate_residual", "attention", "planned contract; no backend implementation evidence", &attention_gate_residual},
    {"attention_with_lse", "attention", "partial family; canonical operation not implemented", &attention_with_lse},
    {"audio_conv1d", "audio", "partial family; canonical operation not implemented", &audio_conv1d},
    {"audio_resample", "audio", "planned contract; no backend implementation evidence", &audio_resample},
    {"causal_conv3d_cache_update", "convolution", "planned contract; no backend implementation evidence", &causal_conv3d_cache_update},
    {"causal_conv_gate_residual", "audio", "planned contract; no backend implementation evidence", &causal_conv_gate_residual},
    {"classifier_free_guidance_combine", "diffusion", "planned contract; no backend implementation evidence", &classifier_free_guidance_combine},
    {"classifier_free_guidance_scheduler_step", "diffusion", "planned contract; no backend implementation evidence", &classifier_free_guidance_scheduler_step},
    {"conv_transpose_overlap_add", "audio", "planned contract; no backend implementation evidence", &conv_transpose_overlap_add},
    {"cross_entropy", "utils", "partial family; canonical operation not implemented", &cross_entropy},
    {"cross_entropy_backward", "utils", "partial family; canonical operation not implemented", &cross_entropy_backward},
    {"ctc_decode", "audio", "planned contract; no backend implementation evidence", &ctc_decode},
    {"deformable_attention", "vision", "planned contract; no backend implementation evidence", &deformable_attention},
    {"deterministic_noise", "diffusion", "planned contract; no backend implementation evidence", &deterministic_noise},
    {"diffusion_scheduler_step", "diffusion", "planned contract; no backend implementation evidence", &diffusion_scheduler_step},
    {"down_projection_residual", "matmul", "planned contract; no backend implementation evidence", &down_projection_residual},
    {"downsample_3d", "convolution", "planned contract; no backend implementation evidence", &downsample_3d},
    {"downsample_conv2d", "convolution", "planned contract; no backend implementation evidence", &downsample_conv2d},
    {"dropout", "utils", "partial family; canonical operation not implemented", &dropout},
    {"embedding_backward", "serving", "partial family; canonical operation not implemented", &embedding_backward},
    {"embedding_lookup", "serving", "partial family; canonical operation not implemented", &embedding_lookup},
    {"flow_euler_step", "diffusion", "planned contract; no backend implementation evidence", &flow_euler_step},
    {"flow_step_action_clamp_denormalize", "vla_world_models", "planned contract; no backend implementation evidence", &flow_step_action_clamp_denormalize},
    {"fp8_gemm", "quantization", "partial family; canonical operation not implemented", &fp8_gemm},
    {"gate_up_projection_swiglu", "matmul", "planned contract; no backend implementation evidence", &gate_up_projection_swiglu},
    {"geglu_projection", "matmul", "planned contract; no backend implementation evidence", &geglu_projection},
    {"gelu", "activations", "partial family; canonical operation not implemented", &gelu},
    {"gelu_backward", "activations", "partial family; canonical operation not implemented", &gelu_backward},
    {"gguf_gemv", "quantization", "partial family; canonical operation not implemented", &gguf_gemv},
    {"glu", "activations", "partial family; canonical operation not implemented", &glu},
    {"grammar_mask", "sampling", "planned contract; no backend implementation evidence", &grammar_mask},
    {"grid_sample", "vision", "planned contract; no backend implementation evidence", &grid_sample},
    {"group_norm_silu", "convolution", "planned contract; no backend implementation evidence", &group_norm_silu},
    {"hadamard", "utils", "partial family; canonical operation not implemented", &hadamard},
    {"indexer_k_gather", "serving", "partial family; canonical operation not implemented", &indexer_k_gather},
    {"istft", "audio", "planned contract; no backend implementation evidence", &istft},
    {"joint_multimodal_attention", "multimodal", "planned contract; no backend implementation evidence", &joint_multimodal_attention},
    {"kv_cache_compact", "serving", "planned contract; no backend implementation evidence", &kv_cache_compact},
    {"kv_cache_copy_blocks_q8_0", "serving", "partial family; canonical operation not implemented", &kv_cache_copy_blocks_q8_0},
    {"kv_cache_gather", "serving", "partial family; canonical operation not implemented", &kv_cache_gather},
    {"kv_cache_gather_q8_0", "serving", "partial family; canonical operation not implemented", &kv_cache_gather_q8_0},
    {"kv_cache_offload", "serving", "planned contract; no backend implementation evidence", &kv_cache_offload},
    {"kv_cache_scatter", "serving", "partial family; canonical operation not implemented", &kv_cache_scatter},
    {"kv_cache_scatter_q8_0", "serving", "partial family; canonical operation not implemented", &kv_cache_scatter_q8_0},
    {"linear_attention", "linear_attention", "partial family; canonical operation not implemented", &linear_attention},
    {"log_mel_spectrogram", "audio", "planned contract; no backend implementation evidence", &log_mel_spectrogram},
    {"logits_bias_penalties_top_k_top_p_sample", "sampling", "planned contract; no backend implementation evidence", &logits_bias_penalties_top_k_top_p_sample},
    {"lora_apply", "matmul", "family-only metadata; canonical adapter not wired", &lora_apply},
    {"lowbit_gemv", "quantization", "partial family; canonical operation not implemented", &lowbit_gemv},
    {"masked_mean_pool_rms_l2", "serving", "partial family; canonical operation not implemented", &masked_mean_pool_rms_l2},
    {"mixed_prefill_decode_attention", "attention", "planned contract; no backend implementation evidence", &mixed_prefill_decode_attention},
    {"moe_all_to_all_dispatch", "collectives", "planned contract; no backend implementation evidence", &moe_all_to_all_dispatch},
    {"moe_grouped_gemm_swiglu", "moe", "planned contract; no backend implementation evidence", &moe_grouped_gemm_swiglu},
    {"moe_route_top_k_prefix_sum_permute", "moe", "planned contract; no backend implementation evidence", &moe_route_top_k_prefix_sum_permute},
    {"moe_route_topk", "moe", "partial family; canonical operation not implemented", &moe_route_topk},
    {"moe_unpermute_weighted_reduce", "moe", "planned contract; no backend implementation evidence", &moe_unpermute_weighted_reduce},
    {"mrope", "attention", "partial family; canonical operation not implemented", &mrope},
    {"multi_codebook_sample", "audio", "planned contract; no backend implementation evidence", &multi_codebook_sample},
    {"multimodal_rope_nd", "multimodal", "planned contract; no backend implementation evidence", &multimodal_rope_nd},
    {"multimodal_stream_deinterleave", "multimodal", "planned contract; no backend implementation evidence", &multimodal_stream_deinterleave},
    {"multimodal_stream_interleave", "multimodal", "planned contract; no backend implementation evidence", &multimodal_stream_interleave},
    {"multistream_logits_codebook_sample", "audio", "planned contract; no backend implementation evidence", &multistream_logits_codebook_sample},
    {"non_max_suppression", "vision", "planned contract; no backend implementation evidence", &non_max_suppression},
    {"nvfp4_gemv", "quantization", "partial family; canonical operation not implemented", &nvfp4_gemv},
    {"overlap_add", "audio", "planned contract; no backend implementation evidence", &overlap_add},
    {"paged_attention_output_projection_residual", "attention", "planned contract; no backend implementation evidence", &paged_attention_output_projection_residual},
    {"paged_attention_q8_0", "attention", "partial family; canonical operation not implemented", &paged_attention_q8_0},
    {"patchify_nd", "diffusion", "planned contract; no backend implementation evidence", &patchify_nd},
    {"patchify_projection_position", "vision", "planned contract; no backend implementation evidence", &patchify_projection_position},
    {"pixel_shuffle", "vision", "planned contract; no backend implementation evidence", &pixel_shuffle},
    {"prefix_append_attention", "attention", "planned contract; no backend implementation evidence", &prefix_append_attention},
    {"qk_norm_rope_attention", "attention", "planned contract; no backend implementation evidence", &qk_norm_rope_attention},
    {"qk_norm_rope_positioned", "norms", "family-only metadata; canonical adapter not wired", &qk_norm_rope_positioned},
    {"qkv_projection_qk_norm_rope_kv_append", "attention", "planned contract; no backend implementation evidence", &qkv_projection_qk_norm_rope_kv_append},
    {"quantize_int4_group", "quantization", "partial family; canonical operation not implemented", &quantize_int4_group},
    {"ragged_pack", "multimodal", "planned contract; no backend implementation evidence", &ragged_pack},
    {"ragged_unpack", "multimodal", "planned contract; no backend implementation evidence", &ragged_unpack},
    {"reduce_scatter_gemm", "collectives", "planned contract; no backend implementation evidence", &reduce_scatter_gemm},
    {"residual_rms_norm_quant", "norms", "planned contract; no backend implementation evidence", &residual_rms_norm_quant},
    {"residual_vector_quantize_decode", "audio", "planned contract; no backend implementation evidence", &residual_vector_quantize_decode},
    {"residual_vector_quantize_encode", "audio", "planned contract; no backend implementation evidence", &residual_vector_quantize_encode},
    {"resize_bicubic", "vision", "planned contract; no backend implementation evidence", &resize_bicubic},
    {"resize_bilinear", "vision", "planned contract; no backend implementation evidence", &resize_bilinear},
    {"resize_normalize_layout_quant", "vision", "planned contract; no backend implementation evidence", &resize_normalize_layout_quant},
    {"rms_norm_backward", "norms", "family-only metadata; canonical adapter not wired", &rms_norm_backward},
    {"rnnt_beam_step", "audio", "planned contract; no backend implementation evidence", &rnnt_beam_step},
    {"rnnt_joiner", "audio", "planned contract; no backend implementation evidence", &rnnt_joiner},
    {"roi_align", "vision", "planned contract; no backend implementation evidence", &roi_align},
    {"rope_3d", "diffusion", "planned contract; no backend implementation evidence", &rope_3d},
    {"rotary_positioned", "attention", "partial family; canonical operation not implemented", &rotary_positioned},
    {"rvq_distance_argmin_residual_update", "audio", "planned contract; no backend implementation evidence", &rvq_distance_argmin_residual_update},
    {"sample_categorical", "sampling", "partial family; canonical operation not implemented", &sample_categorical},
    {"selective_scan", "ssm", "partial family; canonical operation not implemented", &selective_scan},
    {"silu", "activations", "partial family; canonical operation not implemented", &silu},
    {"speculative_verify_accept_compact_kv", "serving", "planned contract; no backend implementation evidence", &speculative_verify_accept_compact_kv},
    {"stft", "audio", "planned contract; no backend implementation evidence", &stft},
    {"streaming_conv1d_state", "audio", "planned contract; no backend implementation evidence", &streaming_conv1d_state},
    {"swiglu_oai", "activations", "partial family; canonical operation not implemented", &swiglu_oai},
    {"temporal_upsample_conv3d", "convolution", "planned contract; no backend implementation evidence", &temporal_upsample_conv3d},
    {"top_k_sample", "sampling", "partial family; canonical operation not implemented", &top_k_sample},
    {"unpatchify_nd", "diffusion", "planned contract; no backend implementation evidence", &unpatchify_nd},
    {"upsample_3d", "convolution", "planned contract; no backend implementation evidence", &upsample_3d},
    {"upsample_conv2d", "convolution", "planned contract; no backend implementation evidence", &upsample_conv2d},
    {"window_rfft_power_mel_log", "audio", "planned contract; no backend implementation evidence", &window_rfft_power_mel_log},
}};

}  // namespace quixicore::rocm::contract_stubs
